BASE_URL = "https://stellarburgers.nomoreparties.site/api/"
REGISTER_URL = BASE_URL + "auth/register"
LOGIN_URL = BASE_URL + "auth/login"
USER_INFO_URL = BASE_URL + "auth/user"
LOGOUT_URL = BASE_URL + "auth/logout"
CREATE_ORDER_URL = BASE_URL + "orders"
GET_INGREDIENT_URL = BASE_URL + "ingredients"